modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "tpaplusplus"
version = "${version}"
displayName = "TPA++"
authors = "SuperRicky14"
description = '''
Compatible, customisable, user friendly TPA mod for Forge, Fabric, NeoForge and Quilt.
'''
#logoFile = ""

[[dependencies.tpaplusplus]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tpaplusplus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tpaplusplus]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tpaplusplus]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[4.12.0,)"
ordering = "AFTER"
side = "BOTH"