modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "tpaplusplus"
version = "${version}"
displayName = "TPAPlusPlus"
authors = ["SuperRicky14", "Half-Nothing"]
description = '''
Compatible, customisable, user friendly TPA mod for NeoForge, Fabric, and Quilt.
'''
#logoFile = ""

[[dependencies.tpaplusplus]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tpaplusplus]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tpaplusplus]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "tpaplusplus.mixins.json"
